---
# # Server # #
Gravedad: 
  X: 0.0
  Y: -20.0
Viento:
  X: 0
  Y: 0

Metros sin danio: 5.0
Degtorad: 0.0174532925199432957
Ancho viga: 0.8

Velocidad movimiento: 5.0
Masa cuerpo estatico: 0.0
Distancia entre vigas: 7

Tamanio gusano: 20
Potencia salto: 3.0
Vida gusano: 100

Tiempo espera dinamita: 99
TIempo espera provision: 45
Tiempo espera viento: 25


# # Comun (lo necesitan cliente y server) # #
Viento maximo:
  X: 10
  Y: -10
Tiempo turno: 60
Tiempo changui: 3

# # Cliente # #
Dimensiones pantalla:
  ancho: 640
  alto: 480
Volumen inicial: 50
Cantidad maxima jugadores: 8
Color jugadores:
  Jugador 1: [255, 255, 0]
  Jugador 2: [255, 50, 0]
  Jugador 3: [0, 0, 255]
  Jugador 4: [50, 205, 50]
  Jugador 5: [255, 165, 0]
  Jugador 6: [255, 0, 255]
  Jugador 7: [0, 255, 255]
  Jugador 8: [255, 255, 255]
Pixels por metro: 20


# # Armas # #
Bazooka:
  ConMira: true
  EsCuerpoACuerpo: false
  TienePotenciaVariable: true
  TieneCuentaRegresiva: false
  EsTeledirigido: false
  EsAfectadaPorViento: true
  Municiones: -1
  Danio:
    Epicentro: 50 
    Radio: 2
  CantidadFragmentos: 0

Mortero:
  ConMira: true
  EsCuerpoACuerpo: false
  TienePotenciaVariable: true
  TieneCuentaRegresiva: false
  EsTeledirigido: false
  EsAfectadaPorViento: true
  Municiones: 10
  Danio: 
    Epicentro: 50
    Radio: 2
  CantidadFragmentos: 6
  DanioFragmento: 
    Epicentro: 10
    Radio: 2

Granada Verde:
  ConMira: true
  EsCuerpoACuerpo: false
  TienePotenciaVariable: true
  TieneCuentaRegresiva: true
  EsTeledirigido: false
  EsAfectadaPorViento: false
  Municiones: -1
  Danio: 
    Epicentro: 30
    Radio: 2
  CantidadFragmentos: 0

Granada Roja:
  ConMira: true
  EsCuerpoACuerpo: false
  TienePotenciaVariable: true
  TieneCuentaRegresiva: true
  EsTeledirigido: false
  EsAfectadaPorViento: false
  Municiones: 10
  Danio: 
    Epicentro: 30
    Radio: 2
  CantidadFragmentos: 6
  DanioFragmento: 
    Epicentro: 10
    Radio: 2

Banana:
  ConMira: true
  EsCuerpoACuerpo: false
  TienePotenciaVariable: true
  TieneCuentaRegresiva: true
  EsTeledirigido: false
  EsAfectadaPorViento: false
  Municiones: 5
  Danio: 
    Epicentro: 70
    Radio: 4
  CantidadFragmentos: 0

Granada Santa:
  ConMira: true
  EsCuerpoACuerpo: false
  TienePotenciaVariable: true
  TieneCuentaRegresiva: true
  EsTeledirigido: false
  EsAfectadaPorViento: false
  Municiones: 2
  Danio: 
    Epicentro: 110
    Radio: 8
  CantidadFragmentos: 0 
  
Dinamita:
  ConMira: false
  EsCuerpoACuerpo: true
  TienePotenciaVariable: false
  TieneCuentaRegresiva: true
  EsTeledirigido: false
  EsAfectadaPorViento: false
  Municiones: 5
  Danio: 
    Epicentro: 50
    Radio: 4
  CantidadFragmentos: 0

Bate de Baseball:
  ConMira: true
  EsCuerpoACuerpo: true
  TienePotenciaVariable: false
  TieneCuentaRegresiva: false
  EsTeledirigido: false
  EsAfectadaPorViento: false
  Municiones: -1
  Danio: 
    Epicentro: 10
    Radio: 0
  CantidadFragmentos: 0

# Agregar cant de misiles
Ataque Aereo:
  ConMira: false
  EsCuerpoACuerpo: false
  TienePotenciaVariable: false
  TieneCuentaRegresiva: false
  EsTeledirigido: true
  EsAfectadaPorViento: true
  Municiones: 2
  Danio: 
    Epicentro: 40
    Radio: 2
  CantidadFragmentos: 0

Teletransportacion:
  ConMira: false
  EsCuerpoACuerpo: false
  TienePotenciaVariable: false
  TieneCuentaRegresiva: false
  EsTeledirigido: true
  EsAfectadaPorViento: false
  Municiones: -1
  Danio: 
    Epicentro: 0
    Radio: 0
  CantidadFragmentos: 0


# # Mapas # #
Cantidad mapas: 3
Nombres mapas: [Pico de la viuda, Torres gemelas, Battlesnax]

Pico de la viuda:
  Dimensiones: [60, 40]
  Cantidad vigas: 18
  Viga 1:
    Tamanio: 6
    Coordenadas: [3.0, 17.0]
    Angulo: 0
  Viga 2:
    Tamanio: 6
    Coordenadas: [11.0, 19.0]
    Angulo: 0
  Viga 3:
    Tamanio: 6
    Coordenadas: [9.0, 15.0]
    Angulo: 0
  Viga 4:
    Tamanio: 6
    Coordenadas: [34.0, 25.0]
    Angulo: 0.78
  Viga 5:
    Tamanio: 6
    Coordenadas: [19.0, 20.0]
    Angulo: 0
  Viga 6:
    Tamanio: 6
    Coordenadas: [15.0, 27.0]
    Angulo: 0
  Viga 7:
    Tamanio: 6
    Coordenadas: [16.0, 14.0]
    Angulo: 0
  Viga 8:
    Tamanio: 6
    Coordenadas: [30.0, 15.0]
    Angulo: 0
  Viga 9:
    Tamanio: 6
    Coordenadas: [24.0, 13.0]
    Angulo: 0
  Viga 10:
    Tamanio: 3
    Coordenadas: [30.0, 33.0]
    Angulo: 0
  Viga 11:
    Tamanio: 6
    Coordenadas: [36.0, 13.0]
    Angulo: 0
  Viga 12:
    Tamanio: 6
    Coordenadas: [44.0, 14.0]
    Angulo: 0
  Viga 13:
    Tamanio: 6
    Coordenadas: [45.0, 27.0]
    Angulo: 0
  Viga 14:
    Tamanio: 6
    Coordenadas: [41.0, 20.0]
    Angulo: 0
  Viga 15:
    Tamanio: 6
    Coordenadas: [26.0, 25.0]
    Angulo: -0.78
  Viga 16:
    Tamanio: 6
    Coordenadas: [51.0, 15.0]
    Angulo: 0
  Viga 17:
    Tamanio: 6
    Coordenadas: [49.0, 19.0]
    Angulo: 0
  Viga 18:
    Tamanio: 6
    Coordenadas: [57.0, 17.0]
    Angulo: 0

  Posicion gusanos: [
    [15.0 ,30.0],
    [5.0 ,19.0],
    [31.0 ,17.0],
    [50.0 ,20.0],
    [45.0 ,15.0],
    [17.0 ,17.0],
  ]

Torres gemelas:
  Dimensiones: [60, 40]
  Cantidad vigas: 18
  Viga 1:
    Tamanio: 6
    Coordenadas: [50.0, 13.0]
    Angulo: 0
  Viga 2:
    Tamanio: 6
    Coordenadas: [11.0, 19.0]
    Angulo: 0
  Viga 3:
    Tamanio: 6
    Coordenadas: [17.0, 22.0]
    Angulo: 1.57
  Viga 4:
    Tamanio: 6
    Coordenadas: [5.0, 25.0]
    Angulo: 0
  Viga 5:
    Tamanio: 6
    Coordenadas: [25.0, 22.0]
    Angulo: 1.57
  Viga 6:
    Tamanio: 6
    Coordenadas: [34.0, 18.0]
    Angulo: 0
  Viga 7:
    Tamanio: 6
    Coordenadas: [5.0, 17.0]
    Angulo: 0
  Viga 8:
    Tamanio: 6
    Coordenadas: [33.0, 22.0]
    Angulo: 0.57
  Viga 9:
    Tamanio: 3
    Coordenadas: [41.0, 16.0]
    Angulo: 0
  Viga 10:
    Tamanio: 6
    Coordenadas: [3.0, 21.0]
    Angulo: 0
  Viga 11:
    Tamanio: 6
    Coordenadas: [44.5, 14.0]
    Angulo: -0.57
  Viga 12:
    Tamanio: 3
    Coordenadas: [36.0, 25.0]
    Angulo: 0
  Viga 13:
    Tamanio: 3
    Coordenadas: [31.0, 24.0]
    Angulo: 0
  Viga 14:
    Tamanio: 3
    Coordenadas: [36.0, 25.0]
    Angulo: 0
  Viga 15:
    Tamanio: 3
    Coordenadas: [44.0, 27.0]
    Angulo: 0
  Viga 16:
    Tamanio: 3
    Coordenadas: [24.0, 15.0]
    Angulo: 0
  Viga 17:
    Tamanio: 3
    Coordenadas: [20.0, 17.0]
    Angulo: 0
  Viga 18:
    Tamanio: 3
    Coordenadas: [33.0, 13.0]
    Angulo: 0

  Posicion gusanos: [
    [11.0 ,21.0],
    [5.0 ,19.0],
    [31.0 ,26.0],
    [50.0 ,15.0],
    [24.0 ,18.0],
    [5.0 ,27.0],
  ]

Battlesnax:
  Dimensiones: [60, 40]
  Cantidad vigas: 13
  Viga 1:
    Tamanio: 6
    Coordenadas: [5.0, 17.0]
    Angulo: 0
  Viga 2:
    Tamanio: 6
    Coordenadas: [30.0, 17.0]
    Angulo: 1.57
  Viga 3:
    Tamanio: 6
    Coordenadas: [30.0, 23.0]
    Angulo: 1.57
  Viga 4:
    Tamanio: 6
    Coordenadas: [27.0, 17.0]
    Angulo: 0
  Viga 5:
    Tamanio: 6
    Coordenadas: [5.0, 10.0]
    Angulo: 0
  Viga 6:
    Tamanio: 6
    Coordenadas: [12.0, 10.0]
    Angulo: 0
  Viga 7:
    Tamanio: 6
    Coordenadas: [25.0, 10.0]
    Angulo: 0
  Viga 8:
    Tamanio: 6
    Coordenadas: [50.0, 10.0]
    Angulo: 0
  Viga 9:
    Tamanio: 3
    Coordenadas: [10.0, 15.0]
    Angulo: 0
  Viga 10:
    Tamanio: 6
    Coordenadas: [45.0, 17.0]
    Angulo: -0.39
  Viga 11:
    Tamanio: 6
    Coordenadas: [37.5, 18.0]
    Angulo: 0
  Viga 12:
    Tamanio: 3
    Coordenadas: [27.0, 13.0]
    Angulo: 0
  Viga 13:
    Tamanio: 3
    Coordenadas: [48.0, 13.0]
    Angulo: 0

  Posicion gusanos: [
    [5.0 ,19.0],
    [50.0 ,19.0],
    [28.5 ,19.0],
    [25.5 ,19.0],
    [51.0 ,19.0],
    [6.0 ,19.0],
  ]
